#!/usr/bin/env python3

import argparse
from urllib.request import urlopen,Request
from urllib.parse   import quote_plus
from bs4            import BeautifulSoup
import sys

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("word")
    args = ap.parse_args()

    response = Request(f"https://en.bab.la/dictionary/english-arabic/{quote_plus(args.word)}", headers={'User-Agent': 'Mozilla/5.0'})
    
    # if quote_plus(args.word).isascii:
    #     response = Request(f"https://en.bab.la/dictionary/english-arabic/{quote_plus(args.word)}", headers={'User-Agent': 'Mozilla/5.0'})
    # else:
    #     response = Request(f"https://en.bab.la/dictionary/arabic-english/{quote_plus(args.word)}", headers={'User-Agent': 'Mozilla/5.0','charset':'utf-8' })

    soup         = BeautifulSoup(urlopen(response).read().decode('utf-8'), "lxml")

    translations = []
    
    def translate(soup):
        try:
            content_container = soup.findAll("div", attrs={"class": "quick-results container"})[0]
            for ul in content_container.findAll("ul", attrs={"class": "sense-group-results"}):
                for a in ul.findAll("a"):
                    if a.text == '\nvolume_up\n':
                        continue
                    else:
                        translations.append(a.text)

        except IndexError:
            print("uhh")

        if not translations:
            sys.exit(1)
        # for t in translations:
            #if t == "volume_up":
            #    continue
            #else:
            # print(t)
        # return translations
    translate(soup)
    
    print(translations)