# Generated by Django 4.0.5 on 2022-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_keyword_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='key_text_out',
            field=models.CharField(default='hello', max_length=150, verbose_name='keyword Output'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
