# Generated by Django 4.0.5 on 2022-06-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabic_keyword_api', '0002_alter_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='key_out_text',
            field=models.CharField(default='Nothing', max_length=150, verbose_name='keyword output'),
        ),
    ]
